### ISSUE TITLE
CL:xanthophore and GO:xanthophore share primary term name

### ISSUE THREAD

**Issue by tberardini** [cmungall/cell-ontology-DO-NOT-USE#182]
xanthophore (CL:0000430) generated 1 warning: The terms xanthophore (GO:0031633) and xanthophore (CL:0000430) share the name or synonym "xanthophore".

Please add the string 'cell' to the CL term name, making it 'xanthophore cell' so that the difference is clear.

GO definition = A chromatophore containing yellow pigment.
CL definition = A pigment cell derived from the neural crest. Contains cartenoid pigments in structures called pterinosomes or xanthosomes. This gives an appearance ranging from a golden yellow to orange and red.

**Comment by cmungall** [comment]
Fixed in https://github.com/obophenotype/cell-ontology/commit/e41507704c07aebaa8f3d6ea31bc375844a4e106

But this is the wrong repository 

should be
https://github.com/obophenotype/cell-ontology

This repo will self destruct in 5.. 4...
